repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.0
    hooks:
      - id: poetry-check
      - name: Poetry lock check
        id: poetry-lock
        args: ["--check"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
      # Update poetry dependencies.
      - name: Poetry lock update
        id: poetry-lock
        stages: [pre-push]
