version: "3.7"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./app-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    expose:
      - "54321"

  app:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - .:/app
    depends_on:
      - db
